# Generated by Django 5.0.3 on 2024-05-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(max_length=50, verbose_name='Catogary'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdetail',
            field=models.CharField(max_length=300, verbose_name='Product detail'),
        ),
    ]
